# Generated by Django 2.0 on 2018-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_hours', models.IntegerField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
