# Generated by Django 2.0 on 2018-08-23 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hours_before_due_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
